feature: implementação do desafio 4
guimiranda0/exercicio-logica pull request #2
Opened 2024-03-17 20:23 UTC by guimiranda0

2024-03-17 21:16 UTC, gabrielmattano approved these changes
Só não testei o contador para chamar os desafios, mas testei no Dartpad cada função de desafio e rodou liso! Parabéns!

2024-03-17 21:26 UTC, guifxb requested changes
Isso aí! Mas seria bom corrigir alguns detalhes, no desafio 4, o número 0 não tá sendo considerado e apesar de ele não ser nem positivo nem negativo, 0 é par e isso precisa ser considerado.
E no desafio 9 pelo enunciado o certo é iniciar uma lista de notas, mas não sei se faria diferença na avaliação ou não.

2024-03-17 22:19 UTC, guimiranda0 commented
Boa galera!! Vou dar uma revisada aqui e já mando a PR pra vocês dnv!

2024-03-18 11:49 UTC, guifxb approved these changes
Boa, agora sim!

2024-03-18 14:16 UTC, gabrielmattano approved these changes

2024-03-18 19:37 UTC, merged